# Generated by Django 4.1.5 on 2023-02-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='LittleLemon',
        ),
    ]
